#!/usr/bin/env python3
"""Generates kernel/src/console/font8x16.h -- the console's font.

    scripts/gen-font.py kernel/src/console/font8x16.h

ASCII and most extra glyphs come from Spleen 8x16 (kernel/src/console/
spleen/, BSD 2-Clause), a font made for terminals: each glyph sits in an
8x16 cell with its own space above and below, so lines of text don't
touch. The few glyphs Spleen doesn't have are drawn as 8x16 pictures
below ('#' = pixel on), in Spleen's style (two-pixel strokes).

The extra code points are exactly the ones anssos_tui::console_has()
(userland/rust/tui/src/lib.rs) promises -- change both together. The
console draws any code point in the generated tables
(console/fbconsole.c) and `?` for anything else.
"""
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
BDF = os.path.join(ROOT, "kernel/src/console/spleen/spleen-8x16.bdf")

# Beyond ASCII: box drawing, the segment ends prompt themes use (Private
# Use Area U+E0B0-U+E0B7: arrows, then rounds), and a few symbols.
EXTRA = "─│┌┐└┘├┤┬┴┼╭╮╯╰" + "".join(chr(c) for c in range(0xE0B0, 0xE0B8)) + "❯❮✔✘·…●█▌▐"

E = "........"
PICTURES = {
    0xE0B4: ("solid right round",
             "###.....", "#####...", "######..", "######..", "#######.", "#######.", "########", "########",
             "########", "########", "#######.", "#######.", "######..", "######..", "#####...", "###....."),
    0xE0B5: ("thin right round",
             "##......", ".###....", "...##...", "....##..", ".....##.", ".....##.", "......##", "......##",
             "......##", "......##", ".....##.", ".....##.", "....##..", "...##...", ".###....", "##......"),
    0xE0B6: ("solid left round",
             ".....###", "...#####", "..######", "..######", ".#######", ".#######", "########", "########",
             "########", "########", ".#######", ".#######", "..######", "..######", "...#####", ".....###"),
    0xE0B7: ("thin left round",
             "......##", "....###.", "...##...", "..##....", ".##.....", ".##.....", "##......", "##......",
             "##......", "##......", ".##.....", ".##.....", "..##....", "...##...", "....###.", "......##"),
    0x276F: ("❯ prompt", E, E,
             ".##.....", ".###....", "..###...", "...###..", "....###.", ".....##.",
             ".....##.", "....###.", "...###..", "..###...", ".###....", ".##.....", E, E),
    0x276E: ("❮ prompt left", E, E,
             ".....##.", "....###.", "...###..", "..###...", ".###....", ".##.....",
             ".##.....", ".###....", "..###...", "...###..", "....###.", ".....##.", E, E),
    0x2714: ("✔ check", E, E, E,
             "......##", "......##", ".....##.", ".....##.", "##..##..", "##..##..", ".####...", ".####...",
             "..##....", E, E, E, E),
    0x2718: ("✘ cross", E, E, E, E,
             "##....##", "###..###", ".######.", "..####..", "..####..", ".######.", "###..###", "##....##",
             E, E, E, E),
}


def load_bdf(path):
    """{code point: 16 row strings}, from a font whose glyphs all fill the
    8x16 cell (Spleen's do: BBX 8 16 0 -4 throughout)."""
    glyphs = {}
    for m in re.finditer(r"ENCODING (\d+)\n.*?BBX (\d+) (\d+) (-?\d+) (-?\d+)\nBITMAP\n(.*?)ENDCHAR",
                         open(path).read(), re.S):
        cp, w, h, xoff, yoff = (int(m.group(i)) for i in range(1, 6))
        assert (w, h, xoff, yoff) == (8, 16, 0, -4), "glyph U+%04X isn't a full 8x16 cell" % cp
        rows = [int(x, 16) for x in m.group(6).split()]
        glyphs[cp] = ["".join("#" if r >> (7 - i) & 1 else "." for i in range(8)) for r in rows]
    return glyphs


def byte(row):
    """Bit 0 = leftmost pixel, the order console/fbconsole.c draws in."""
    return sum(1 << x for x, ch in enumerate(row) if ch == "#")


def row_bytes(rows):
    assert len(rows) == 16 and all(len(r) == 8 for r in rows)
    return ", ".join("0x%02X" % byte(r) for r in rows)


spleen = load_bdf(BDF)
out = ['''/* The console's font: 8x16 glyphs, one byte per row, top row first,
 * bit 0 = leftmost pixel.
 *
 * Generated by scripts/gen-font.py -- edit that and rerun rather than
 * these bytes. Glyphs are from Spleen 8x16
 * (kernel/src/console/spleen/, Copyright (c) 2018-2026 Frederic Cambus,
 * BSD 2-Clause -- see spleen/LICENSE), except U+E0B4-U+E0B7, U+276E,
 * U+276F, U+2714 and U+2718, which scripts/gen-font.py draws itself. */
#ifndef CONSOLE_FONT8X16_H
#define CONSOLE_FONT8X16_H

#include <stdint.h>

/* U+0000-U+007F. Control characters are blank. */
static const uint8_t font8x16_ascii[128][16] = {''']
for cp in range(128):
    if 32 <= cp < 127:
        out.append("    {%s}, /* %r */" % (row_bytes(spleen[cp]), chr(cp)))
    else:
        out.append("    {0},")
out.append('''};

struct font_glyph {
    uint32_t cp;
    uint8_t rows[16];
};

/* Everything beyond ASCII, sorted by code point. */
static const struct font_glyph font8x16_ext[] = {''')
for cp in sorted(ord(c) for c in EXTRA):
    if cp in PICTURES:
        name, rows = PICTURES[cp][0], PICTURES[cp][1:]
    else:
        name, rows = "%s (Spleen)" % chr(cp) if cp < 0xE000 else "powerline (Spleen)", spleen[cp]
    out.append("    {0x%04X, {%s}}, /* U+%04X %s */" % (cp, row_bytes(rows), cp, name))
out.append('''};

#endif''')
open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("%d extra glyphs (%d drawn here): %s" % (len(EXTRA), len(PICTURES), EXTRA))
