#!/usr/bin/env python3
"""Generates kernel/src/console/font8x8_ext.h -- the console's glyphs
beyond ASCII -- from the 8x8 pictures below ('#' = pixel on).

    scripts/gen-font-ext.py kernel/src/console/font8x8_ext.h

To add or change a glyph, edit its picture and rerun; the console draws
any code point in the generated table (console/fbconsole.c).
"""
G = {}
def g(cp, name, *rows):
    assert len(rows) == 8 and all(len(r) == 8 for r in rows), name
    G[cp] = (name, rows)

E = "........"
# --- box drawing: lines on column 3 / row 3, one pixel thick ---
H = "########"; V = "...#...."
g(0x2500, "─ horizontal", E,E,E,H,E,E,E,E)
g(0x2502, "│ vertical", V,V,V,V,V,V,V,V)
g(0x250C, "┌ down-right", E,E,E,"...#####",V,V,V,V)
g(0x2510, "┐ down-left", E,E,E,"####....",V,V,V,V)
g(0x2514, "└ up-right", V,V,V,"...#####",E,E,E,E)
g(0x2518, "┘ up-left", V,V,V,"####....",E,E,E,E)
g(0x251C, "├ vertical-right", V,V,V,"...#####",V,V,V,V)
g(0x2524, "┤ vertical-left", V,V,V,"####....",V,V,V,V)
g(0x252C, "┬ horizontal-down", E,E,E,H,V,V,V,V)
g(0x2534, "┴ horizontal-up", V,V,V,H,E,E,E,E)
g(0x253C, "┼ cross", V,V,V,H,V,V,V,V)
g(0x256D, "╭ rounded down-right", E,E,E,"....####",V,V,V,V)
g(0x256E, "╮ rounded down-left", E,E,E,"###.....",V,V,V,V)
g(0x256F, "╯ rounded up-left", V,V,V,"###.....",E,E,E,E)
g(0x2570, "╰ rounded up-right", V,V,V,"....####",E,E,E,E)
# --- segment ends (Private Use Area, the code points prompt themes use) ---
g(0xE0B0, " solid right arrow", "#.......","###.....","#####...","#######.","#######.","#####...","###.....","#.......")
g(0xE0B1, " thin right arrow",  "#.......",".##.....","...##...",".....##.",".....##.","...##...",".##.....","#.......")
g(0xE0B2, " solid left arrow",  ".......#",".....###","...#####",".#######",".#######","...#####",".....###",".......#")
g(0xE0B3, " thin left arrow",   ".......#",".....##.","...##...",".##.....",".##.....","...##...",".....##.",".......#")
g(0xE0B4, " solid right round", "###.....","#####...","######..","#######.","#######.","######..","#####...","###.....")
g(0xE0B5, " thin right round",  "##......","..##....","....#...",".....#..",".....#..","....#...","..##....","##......")
g(0xE0B6, " solid left round",  ".....###","...#####","..######",".#######",".#######","..######","...#####",".....###")
g(0xE0B7, " thin left round",   "......##","....##..","...#....","..#.....","..#.....","...#....","....##..","......##")
# --- symbols ---
g(0x276F, "❯ prompt", ".##.....","..##....","...##...","....##..","...##...","..##....",".##.....",E)
g(0x276E, "❮ prompt left", ".....##.","....##..","...##...","..##....","...##...","....##..",".....##.",E)
g(0x2714, "✔ check", E,"......##",".....##.","##..##..",".####...","..##....",E,E)
g(0x2718, "✘ cross", E,".##..##.","..####..","...##...","..####..",".##..##.",E,E)
g(0x00B7, "· middle dot", E,E,E,"...##...","...##...",E,E,E)
g(0x2026, "… ellipsis", E,E,E,E,E,E,"##.##.##",E)
g(0x25CF, "● circle", E,"..####..",".######.",".######.",".######.",".######.","..####..",E)
g(0x2588, "█ full block", H,H,H,H,H,H,H,H)
g(0x258C, "▌ left half block", *(["####...."]*8))
g(0x2590, "▐ right half block", *(["....####"]*8))

def byte(row):
    return sum(1 << x for x, ch in enumerate(row) if ch == '#')

out = ['''/* Extra 8x8 glyphs beyond font8x8_basic.h's ASCII: box drawing, the
 * segment-end arrows and rounds prompt themes use (Private Use Area
 * U+E0B0-U+E0B7), and a few symbols (prompt chevrons, check/cross, dot,
 * ellipsis, blocks). Same layout as font8x8_basic: one byte per row, top
 * row first, bit 0 = leftmost pixel. Box lines run along column 3 and
 * row 3 so they join up.
 *
 * Generated by scripts/gen-font-ext.py from 8x8 pictures -- edit those
 * and rerun rather than these bytes. */
#ifndef CONSOLE_FONT8X8_EXT_H
#define CONSOLE_FONT8X8_EXT_H

#include <stdint.h>

struct ext_glyph {
    uint32_t cp;
    uint8_t rows[8];
};

static const struct ext_glyph font8x8_ext[] = {''']
for cp in sorted(G):
    name, rows = G[cp]
    bs = ", ".join("0x%02X" % byte(r) for r in rows)
    out.append("    {0x%04X, {%s}}, /* U+%04X %s */" % (cp, bs, cp, name))
out.append('''};

#endif''')
import sys
open(sys.argv[1], 'w').write("\n".join(out) + "\n")
print(len(G), "glyphs:", "".join(chr(c) for c in sorted(G)))
